module.exports = [
  { errorCode: 1016, errorMessage: "License Error: Could not find license." },
  { errorCode: 3000, errorMessage: "Unknown error" },
  { errorCode: 3001, errorMessage: "Unsupported manifest format" },
  { errorCode: 3002, errorMessage: "Segment contains no data" },
  { errorCode: 3003, errorMessage: "Corrupt tfdt version" },
  { errorCode: 3004, errorMessage: "No URL for segment found" },
  { errorCode: 3005, errorMessage: "No URL to manifest given" },
  { errorCode: 3006, errorMessage: "Could not load manifest, got HTTP status code " },
  { errorCode: 3011, errorMessage: "DRM: License request failed with HTTP status " },
  { errorCode: 3012, errorMessage: "DRM: Invalid header name/value pair for PlayReady license request" },
  { errorCode: 3013, errorMessage: "DRM: Key or KeyID is missing" },
  { errorCode: 3014, errorMessage: "DRM: Key size not supported" },
  { errorCode: 3016, errorMessage: "DRM: Unable to instantiate a key system supporting the required combinations" },
  { errorCode: 3017, errorMessage: "DRM: Unable to create or initialize key session" },
  { errorCode: 3018, errorMessage: "DRM: Failed to create and initialize a MediaKeys object" },
  { errorCode: 3019, errorMessage: "DRM: Key or KeyID is missing" },
  { errorCode: 3020, errorMessage: "DRM: Key Error" },
  { errorCode: 3021, errorMessage: 'DRM: Key System not supported' },
  { errorCode: 3022, errorMessage: 'Error with the manifest, maybe MPD is not valid' },
  { errorCode: 3023, errorMessage: 'A network error occurred. The reasons might be: No internet connection, domain name could not be resolved, the server refused the connection or CORS is not enabled' },
  { errorCode: 3024, errorMessage: 'Manifest download has timed out' },
  { errorCode: 3025, errorMessage: 'Segment download has timed out' },
  { errorCode: 3026, errorMessage: 'Progressive stream has timed out' },
  { errorCode: 3027, errorMessage: 'DRM: Certificate Error' },
  { errorCode: 3028, errorMessage: 'Progressive stream type not supported or the stream has an error' },
  { errorCode: 3029, errorMessage: 'HLS stream has an error' },
  { errorCode: 3030, errorMessage: 'Could not skip gap' },
  { errorCode: 3031, errorMessage: 'DRM: Could not parse Fairplay certificate' },
  { errorCode: 3032, errorMessage: 'No supported source found within manifest' },
  { errorCode: 3033, errorMessage: 'DRM: License server URL not found (LA_URL, getLicenseServerUrl or manifest)' },
  { errorCode: 3034, errorMessage: 'DRM: No DRM configuration provided for protected stream' },
  { errorCode: 3035, errorMessage: 'Player had too many consecutive errors' },
  { errorCode: 2000, errorMessage: 'Unknown error: {{0}}' },
  { errorCode: 2001, errorMessage: 'DRM Error occured: {{0}}' },
  { errorCode: 6000, errorMessage: 'INTERNAL ONLY: RESTART PLAYER' },
];
